---
output:
  bookdown::pdf_document2:
    fig_caption: yes
    toc: FALSE
    toc_depth: 3
    fontsize: 12pt
    latex_engine: xelatex
bibliography: "Bachelor_quellen.bib"
csl: european-journal-of-taxonomy.csl
citation_package: biblatex
link-citations: yes
urlcolor: RoyalBlue
linkcolor: RoyalBlue
always_allow_html: TRUE
header-includes:
  \usepackage{float}
  \usepackage{longtable}
  \usepackage[ngerman]{babel}
  \usepackage[onehalfspacing]{setspace}
  \usepackage{colortbl}
  \usepackage[utf8]{inputenc}
  \renewcommand{\listfigurename}{Abbildungsverzeichnis}
  \renewcommand{\listtablename}{Tabellenverzeichnis}
  \pagenumbering{Roman}
  \usepackage[]{hyperref}
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(kableExtra)
library(ggplot2)
library(mdthemes)
```

\pagenumbering{arabic}

```{r, child='Deckblatt.Rmd'}
```

\pagebreak



\hypersetup{linkcolor=black}
\tableofcontents

\pagebreak

\listoffigures

\pagebreak

\listoftables

\pagebreak

# Abk체rzungsverzeichnis

```{r abk체rzungsverzeichnis, message = FALSE, warning=FALSE}
Abkz <- read.csv2("Abk체rzungsverzeichnis.csv", header = FALSE, fileEncoding="latin1")
kable(Abkz, booktabs = TRUE, col.names = NULL, longtable = T) %>%
  column_spec(1, width = "2.2in") %>%
  column_spec(2, width = "3.5in") %>%
  kable_styling(latex_options = c("repeat_header"), repeat_header_continued = "\\textit{(fortgesetzt auf der n채chsten Seite...)}", repeat_header_text = "\\textit{(fortgesetzt)}")

  
```


\pagebreak

\hypersetup{linkcolor=RoyalBlue}



```{r, child=c('Einleitung.Rmd', 'Methoden.Rmd', "Ergebnisse(neu).Rmd", "Diskussion.Rmd")}
```

\pagebreak



```{r, child=c("Anhang.Rmd") }

```



# Literaturverzeichniss